# fly.toml app configuration file generated for search6 on 2023-04-26T18:08:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "search6"
primary_region = "den"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  image = "ghcr.io/randomairborne/search6:latest"

[env]
  GUILD_ID = "302094807046684672"
  PRIMARY_REGION = "den"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "requests"
    hard_limit = 2500
    soft_limit = 2000

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/?id=788222689126776832"
    protocol = "http"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/card?id=788222689126776832"
    protocol = "http"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/"
    protocol = "http"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/search6.png"
    protocol = "http"